version: '3.7'
services:
  iddb:
    image: postgres:14-alpine
    ports:
      - '5401:5432'
    volumes:
      - ./id/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    command: ["postgres", "-c", "log_statement=all"]
  musicdb:
    image: postgres:14-alpine
    ports:
      - '5402:5432'
    volumes:
      - ./music/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    command: ["postgres", "-c", "log_statement=all"]
